CREATE DATABASE IF NOT EXISTS mid;
USE mid;

CREATE TABLE IF NOT EXISTS users (
  USERNAME VARCHAR(50) PRIMARY KEY,
  FIRST_NAME VARCHAR(100) NOT NULL,
  LAST_NAME VARCHAR(100) NOT NULL,
  EMAIL VARCHAR(150) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS login_account (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(50) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  CONSTRAINT fk_login_user FOREIGN KEY (username) REFERENCES users(USERNAME)
);

CREATE TABLE IF NOT EXISTS student_profiles (
  USERNAME VARCHAR(50) PRIMARY KEY,
  GPA DECIMAL(3,2) DEFAULT NULL,
  HEIGHT DECIMAL(5,2) DEFAULT NULL,
  ORGANIZATIONAL_ROLE VARCHAR(150) DEFAULT 'Anggota BEM FILKOM',
  PHOTO_URL VARCHAR(255) DEFAULT '',
  CONSTRAINT fk_profile_user FOREIGN KEY (USERNAME) REFERENCES users(USERNAME)
);

CREATE TABLE IF NOT EXISTS student_semester_grades (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  student_nim VARCHAR(50) NOT NULL,
  semester INT NOT NULL,
  course_name VARCHAR(150) NOT NULL,
  score DECIMAL(5,2) NOT NULL,
  credits INT NOT NULL,
  grade_note VARCHAR(3) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
